import {
  Palette,
  Code,
  Search,
  RefreshCw,
  ShoppingBag,
  Target,
  Wrench,
  Megaphone,
  Settings,
  MapPin,
  FileText,
  ClipboardCheck,
  Smartphone,
  Zap,
  Briefcase,
  TrendingUp,
  Building2,
  Hotel,
  Rocket,
  Plane,
  UtensilsCrossed,
  KeyRound,
  LayoutTemplate,
  Layers,
  Plug,
  Monitor,
  Shield,
  Gauge,
  PenTool,
  MousePointerClick,
  LineChart,
  Store,
  Scale,
  Heart,
  GraduationCap,
  Sparkles,
  Car,
  Ticket,
  Users,
  HardHat,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const iconMap: Record<string, LucideIcon> = {
  palette: Palette,
  code: Code,
  search: Search,
  "refresh-cw": RefreshCw,
  "shopping-bag": ShoppingBag,
  target: Target,
  wrench: Wrench,
  megaphone: Megaphone,
  settings: Settings,
  "map-pin": MapPin,
  "file-text": FileText,
  "clipboard-check": ClipboardCheck,
  smartphone: Smartphone,
  zap: Zap,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  building: Building2,
  hotel: Hotel,
  rocket: Rocket,
  plane: Plane,
  utensils: UtensilsCrossed,
  key: KeyRound,
  "layout-template": LayoutTemplate,
  layers: Layers,
  plug: Plug,
  monitor: Monitor,
  shield: Shield,
  gauge: Gauge,
  "pen-tool": PenTool,
  "mouse-pointer-click": MousePointerClick,
  "line-chart": LineChart,
  store: Store,
  scale: Scale,
  heart: Heart,
  "graduation-cap": GraduationCap,
  sparkles: Sparkles,
  car: Car,
  ticket: Ticket,
  users: Users,
  "hard-hat": HardHat,
};

type IconProps = {
  name: string;
  className?: string;
};

export function Icon({ name, className }: IconProps) {
  const Lucide = iconMap[name] ?? Search;
  return <Lucide className={cn("h-5 w-5", className)} aria-hidden />;
}
