-- Phase D: Resource subtype AI assistants (additive)

ALTER TYPE "AIContentEntityType" ADD VALUE IF NOT EXISTS 'GUIDE';
ALTER TYPE "AIContentEntityType" ADD VALUE IF NOT EXISTS 'COMPARISON';
ALTER TYPE "AIContentEntityType" ADD VALUE IF NOT EXISTS 'CHECKLIST';
ALTER TYPE "AIContentEntityType" ADD VALUE IF NOT EXISTS 'GLOSSARY';
ALTER TYPE "AIContentEntityType" ADD VALUE IF NOT EXISTS 'TEMPLATE';
ALTER TYPE "AIContentEntityType" ADD VALUE IF NOT EXISTS 'TOOL';
