/**
 * Default Source Pack definitions (data, not algorithm logic).
 */

export const DEFAULT_SOURCE_PACKS = [
  {
    slug: "seo-search",
    name: "SEO & Search",
    description: "Official search guidance, standards, and reputable SEO research themes.",
    priority: 10,
    officialDomains: ["developers.google.com", "search.google", "w3.org"],
    keywords: ["SEO", "search", "Core Web Vitals", "indexing", "crawl"],
    newsQueries: ["search engine guidance website", "Core Web Vitals update"],
    rssFeeds: [] as string[],
  },
  {
    slug: "performance",
    name: "Website Performance",
    description: "Performance, CWV, and speed-related developments.",
    priority: 20,
    officialDomains: ["web.dev", "developers.google.com"],
    keywords: ["performance", "Core Web Vitals", "LCP", "INP", "CLS"],
    newsQueries: ["Core Web Vitals", "website performance"],
    rssFeeds: [] as string[],
  },
  {
    slug: "wordpress",
    name: "WordPress",
    description: "WordPress platform updates and ecosystem changes.",
    priority: 30,
    officialDomains: ["wordpress.org", "developer.wordpress.org"],
    keywords: ["WordPress", "Gutenberg", "WordPress security"],
    newsQueries: ["WordPress release", "WordPress security"],
    rssFeeds: ["https://wordpress.org/news/feed/"],
  },
  {
    slug: "shopify",
    name: "Shopify",
    description: "Shopify commerce platform updates and developer docs themes.",
    priority: 30,
    officialDomains: ["shopify.dev", "www.shopify.com"],
    keywords: ["Shopify", "ecommerce", "checkout"],
    newsQueries: ["Shopify update", "Shopify checkout"],
    rssFeeds: [],
  },
  {
    slug: "ecommerce",
    name: "E-commerce",
    description: "Commerce platforms, catalogue, and conversion themes.",
    priority: 40,
    officialDomains: [],
    keywords: ["ecommerce", "Shopify", "BigCommerce", "product page"],
    newsQueries: ["ecommerce platform update"],
    rssFeeds: [],
  },
  {
    slug: "hospitality",
    name: "Hospitality & Short-Term Rentals",
    description: "Hospitality and direct-booking technology developments.",
    priority: 50,
    officialDomains: [],
    keywords: ["hospitality", "vacation rental", "direct booking", "OTA"],
    newsQueries: ["vacation rental technology", "hospitality booking"],
    rssFeeds: [],
  },
  {
    slug: "local-business",
    name: "Local Business",
    description: "Local search and local service business visibility.",
    priority: 40,
    officialDomains: ["developers.google.com"],
    keywords: ["local SEO", "Google Business Profile", "local search"],
    newsQueries: ["local SEO", "Google Business Profile"],
    rssFeeds: [],
  },
  {
    slug: "ai-search-tech",
    name: "AI / Search Technology",
    description: "AI-assisted search and web technology developments relevant to publishers.",
    priority: 60,
    officialDomains: [],
    keywords: ["AI search", "AI Overview", "generative search"],
    newsQueries: ["AI search websites", "generative search SEO"],
    rssFeeds: [],
  },
] as const;
