/** Server-side field allowlists — models never choose mutable fields. */

export const SERVICE_PROTECTED_FIELDS = new Set([
  "id",
  "status",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "createdById",
  "updatedById",
  "featured",
  "navigationFeatured",
  "displayOrder",
  "visualVariant",
  "noIndex",
  "canonicalOverride",
  "slug",
  "href",
]);

/** Fields Service AI may propose (never protected). */
export const SERVICE_FIELD_ALLOWLIST = new Set([
  "summary",
  "description",
  "tagline",
  "narrativeTitle",
  "narrative",
  "seoConnection",
  "audience",
  "platformsNote",
  "capabilities",
  "idealFor",
  "problems",
  "deliverables",
  "process",
  "evaluationItems",
  "faqs",
  "ctaTitle",
  "ctaDescription",
  "primaryCtaLabel",
  "primaryCtaHref",
  "secondaryCtaLabel",
  "secondaryCtaHref",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedSolutionSlugs",
  "relatedPlatformSlugs",
  "relatedProjectSlugs",
  "relatedServiceSlugs",
  "relatedSeoSlugs",
  // title/shortTitle: suggest only via dedicated flows — excluded from full rewrite apply
]);

export const SERVICE_FIELD_LABELS: Record<string, string> = {
  summary: "Summary",
  description: "Description",
  tagline: "Tagline",
  narrativeTitle: "Narrative title",
  narrative: "Narrative",
  seoConnection: "SEO connection",
  audience: "Audience",
  platformsNote: "Platforms note",
  capabilities: "Capabilities",
  idealFor: "Ideal for",
  problems: "Problems addressed",
  deliverables: "Deliverables",
  process: "Process",
  evaluationItems: "Evaluation items",
  faqs: "FAQs",
  ctaTitle: "CTA title",
  ctaDescription: "CTA description",
  primaryCtaLabel: "Primary CTA label",
  primaryCtaHref: "Primary CTA href",
  secondaryCtaLabel: "Secondary CTA label",
  secondaryCtaHref: "Secondary CTA href",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedSolutionSlugs: "Related solutions",
  relatedPlatformSlugs: "Related platforms",
  relatedProjectSlugs: "Related work",
  relatedServiceSlugs: "Related services",
  relatedSeoSlugs: "Related SEO pages",
};

export const SOLUTION_PROTECTED_FIELDS = new Set([
  "id",
  "status",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "createdById",
  "updatedById",
  "featured",
  "displayOrder",
  "noIndex",
  "canonicalOverride",
  "slug",
  "pageKind",
]);

export const SOLUTION_FIELD_ALLOWLIST = new Set([
  "shortDescription",
  "eyebrow",
  "heroStatement",
  "heroSupporting",
  "problemSymptoms",
  "possibleCauses",
  "whatWeReview",
  "process",
  "measurementPoints",
  "relatedServiceReasons",
  "faqs",
  "ctaTitle",
  "ctaDescription",
  "primaryCtaLabel",
  "primaryCtaHref",
  "secondaryCtaLabel",
  "secondaryCtaHref",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedPlatformSlugs",
  "relatedIndustrySlugs",
  "relatedProjectSlugs",
  "relatedArticleSlugs",
  "relatedSolutions",
  // relatedServiceHrefs — suggest additions only; never wipe required relations via apply
]);

export const SOLUTION_FIELD_LABELS: Record<string, string> = {
  shortDescription: "Short description",
  eyebrow: "Eyebrow",
  heroStatement: "Hero statement",
  heroSupporting: "Hero supporting",
  problemSymptoms: "Problem symptoms",
  possibleCauses: "Possible causes",
  whatWeReview: "What we review",
  process: "Approach / process",
  measurementPoints: "Measurement points",
  relatedServiceReasons: "Why each Service is relevant",
  faqs: "FAQs",
  ctaTitle: "CTA title",
  ctaDescription: "CTA description",
  primaryCtaLabel: "Primary CTA label",
  primaryCtaHref: "Primary CTA href",
  secondaryCtaLabel: "Secondary CTA label",
  secondaryCtaHref: "Secondary CTA href",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedPlatformSlugs: "Related platforms",
  relatedIndustrySlugs: "Related industries",
  relatedProjectSlugs: "Related work",
  relatedArticleSlugs: "Related insights",
  relatedSolutions: "Related solutions",
};

export const PLATFORM_PROTECTED_FIELDS = new Set([
  "id",
  "status",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "createdById",
  "updatedById",
  "featured",
  "navigationFeatured",
  "displayOrder",
  "prominence",
  "verifiedExperience",
  "platformMatch",
  "noIndex",
  "canonicalOverride",
  "slug",
  "href",
  "lastReviewedAt", // server-set only after researched apply
]);

export const PLATFORM_FIELD_ALLOWLIST = new Set([
  "summary",
  "description",
  "tagline",
  "audiences",
  "whenItFits",
  "capabilities",
  "challenges",
  "seoSection",
  "conversionNote",
  "migrationNote",
  "faqs",
  "ctaTitle",
  "ctaDescription",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceHrefs",
  "relatedSeoHrefs",
]);

export const PLATFORM_FIELD_LABELS: Record<string, string> = {
  summary: "Summary",
  description: "Description",
  tagline: "Tagline",
  audiences: "Audiences",
  whenItFits: "When it fits",
  capabilities: "Capabilities",
  challenges: "Challenges / trade-offs",
  seoSection: "SEO section",
  conversionNote: "Conversion note",
  migrationNote: "Migration note",
  faqs: "FAQs",
  ctaTitle: "CTA title",
  ctaDescription: "CTA description",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceHrefs: "Related services",
  relatedSeoHrefs: "Related SEO routes",
};

export const INDUSTRY_PROTECTED_FIELDS = new Set([
  "id",
  "status",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "createdById",
  "updatedById",
  "featured",
  "displayOrder",
  "group",
  "hasVerifiedProjectExperience",
  "noIndex",
  "canonicalOverride",
  "slug",
  "icon",
]);

export const INDUSTRY_FIELD_ALLOWLIST = new Set([
  "description",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceLinks",
  "relatedSolutionSlugs",
]);

export const INDUSTRY_FIELD_LABELS: Record<string, string> = {
  description: "Description",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceLinks: "Related services",
  relatedSolutionSlugs: "Related solutions",
};

export const WORK_PROTECTED_FIELDS = new Set([
  "id",
  "status",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "createdById",
  "updatedById",
  "featured",
  "featuredHomepage",
  "featuredWorkArchive",
  "displayOrder",
  "slug",
  "clientName",
  "name",
  "approvedForAI",
  "approvedProjectFacts",
  "designNotes",
  "developmentNotes",
  "seoNotes",
  "noIndex",
  "canonicalOverride",
  "platformId", // suggest only via relations — apply carefully with verification
]);

/** Public Case Study prose AI may propose from verified facts */
export const WORK_FIELD_ALLOWLIST = new Set([
  "shortDescription",
  "overview",
  "challenge",
  "solution",
  "approach",
  "resultSummary",
  "results",
  "measurableResults",
  "heroStatement",
  "challenges",
  "approachSteps",
  "solutionPoints",
  "highlights",
  "platformContext",
  "outcomeHeading",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceHrefs",
  "platformLabel",
  "servicesLabels",
  "technologies",
]);

export const WORK_FIELD_LABELS: Record<string, string> = {
  shortDescription: "Short description",
  overview: "Overview",
  challenge: "Challenge",
  solution: "Solution",
  approach: "Approach",
  resultSummary: "Result summary",
  results: "Results",
  measurableResults: "Measurable results",
  heroStatement: "Hero statement",
  challenges: "Challenge points",
  approachSteps: "Approach steps",
  solutionPoints: "Solution points",
  highlights: "Highlights",
  platformContext: "Platform context",
  outcomeHeading: "Outcome heading",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceHrefs: "Related services",
  platformLabel: "Platform label",
  servicesLabels: "Service labels",
  technologies: "Technologies",
};

export const TESTIMONIAL_PROTECTED_FIELDS = new Set([
  "id",
  "legacyId",
  "status",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "createdById",
  "updatedById",
  "verified",
  "featured",
  "displayOrder",
  "name",
  "role",
  "company",
  "internalSource",
  "internalSourceUrl",
  "internalVerificationNote",
  "originalQuote",
  "avatarPath",
]);

/** Extremely narrow — excerpt, safe quote format, themes, work relation */
export const TESTIMONIAL_FIELD_ALLOWLIST = new Set([
  "displayExcerpt",
  "quote", // only via FORMAT_QUOTE with integrity check
  "themesJson",
  "workProjectId",
]);

export const TESTIMONIAL_FIELD_LABELS: Record<string, string> = {
  displayExcerpt: "Display excerpt",
  quote: "Formatted quote",
  themesJson: "Themes",
  workProjectId: "Related Case Study",
};

/** Shared CMS columns Resource assistants may propose */
const RESOURCE_CMS_PROTECTED = [
  "id",
  "type",
  "status",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "createdById",
  "updatedById",
  "slug",
  "href",
  "featured",
  "featuredOnResources",
  "featuredOrder",
  "noIndex",
  "canonicalOverride",
  "payload",
] as const;

export const GUIDE_PROTECTED_FIELDS = new Set<string>([
  ...RESOURCE_CMS_PROTECTED,
  "sectionIds",
]);

export const GUIDE_FIELD_ALLOWLIST = new Set([
  "title",
  "description",
  "deck",
  "intro",
  "faqs",
  "sections",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceHrefs",
  "relatedSolutionSlugs",
  "relatedInsightSlugs",
  "relatedResourceIds",
  "readingTime",
]);

export const GUIDE_FIELD_LABELS: Record<string, string> = {
  title: "Title",
  description: "Description",
  deck: "Deck",
  intro: "Intro",
  faqs: "FAQs",
  sections: "Sections",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceHrefs: "Related services",
  relatedSolutionSlugs: "Related solutions",
  relatedInsightSlugs: "Related insights",
  relatedResourceIds: "Related resources",
  readingTime: "Reading time",
};

export const COMPARISON_PROTECTED_FIELDS = new Set<string>([
  ...RESOURCE_CMS_PROTECTED,
  "criterionIds",
  "matrixIds",
]);

export const COMPARISON_FIELD_ALLOWLIST = new Set([
  "title",
  "description",
  "deck",
  "summary",
  "quickFitA",
  "quickFitB",
  "comparisonCriteria",
  "decisionMatrix",
  "sections",
  "bestForA",
  "bestForB",
  "decisionQuestions",
  "tradeoffs",
  "decisionGuidance",
  "faqs",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedPlatformSlugs",
  "relatedServiceHrefs",
  "relatedSolutionSlugs",
  "relatedInsightSlugs",
]);

export const COMPARISON_FIELD_LABELS: Record<string, string> = {
  title: "Title",
  description: "Description",
  deck: "Deck",
  summary: "Summary",
  quickFitA: "Quick fit A",
  quickFitB: "Quick fit B",
  comparisonCriteria: "Criteria",
  decisionMatrix: "Decision matrix",
  sections: "Sections",
  bestForA: "Best for A",
  bestForB: "Best for B",
  decisionQuestions: "Decision questions",
  tradeoffs: "Trade-offs",
  decisionGuidance: "Decision guidance",
  faqs: "FAQs",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedPlatformSlugs: "Related platforms",
  relatedServiceHrefs: "Related services",
  relatedSolutionSlugs: "Related solutions",
  relatedInsightSlugs: "Related insights",
};

export const CHECKLIST_PROTECTED_FIELDS = new Set<string>([
  ...RESOURCE_CMS_PROTECTED,
  "itemIds",
  "sectionIds",
  "subgroupIds",
]);

export const CHECKLIST_FIELD_ALLOWLIST = new Set([
  "title",
  "description",
  "subtitle",
  "intro",
  "sections",
  "itemUpdates",
  "newItemSuggestions",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceHrefs",
  "relatedSolutionSlugs",
  "relatedInsightSlugs",
]);

export const CHECKLIST_FIELD_LABELS: Record<string, string> = {
  title: "Title",
  description: "Description",
  subtitle: "Subtitle",
  intro: "Intro",
  sections: "Sections",
  itemUpdates: "Item wording updates",
  newItemSuggestions: "Suggested new items",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceHrefs: "Related services",
  relatedSolutionSlugs: "Related solutions",
  relatedInsightSlugs: "Related insights",
};

export const GLOSSARY_PROTECTED_FIELDS = new Set<string>([
  ...RESOURCE_CMS_PROTECTED,
  "glossaryTopicGroup",
]);

export const GLOSSARY_FIELD_ALLOWLIST = new Set([
  "title",
  "description",
  "shortDefinition",
  "acronym",
  "aliases",
  "fullExplanation",
  "whyItMatters",
  "example",
  "commonMisconceptions",
  "relatedTermSlugs",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceHrefs",
  "relatedSolutionSlugs",
  "relatedInsightSlugs",
]);

export const GLOSSARY_FIELD_LABELS: Record<string, string> = {
  title: "Term",
  description: "Description",
  shortDefinition: "Short definition",
  acronym: "Acronym",
  aliases: "Aliases",
  fullExplanation: "Full explanation",
  whyItMatters: "Why it matters",
  example: "Example",
  commonMisconceptions: "Common misconceptions",
  relatedTermSlugs: "Related terms",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceHrefs: "Related services",
  relatedSolutionSlugs: "Related solutions",
  relatedInsightSlugs: "Related insights",
};

export const TEMPLATE_PROTECTED_FIELDS = new Set<string>([
  ...RESOURCE_CMS_PROTECTED,
  "fieldIds",
  "sectionIds",
  "optionValues",
  "showWhenAny",
  "storageKey",
  "storageVersion",
]);

export const TEMPLATE_FIELD_ALLOWLIST = new Set([
  "title",
  "description",
  "subtitle",
  "intro",
  "sectionCopyUpdates",
  "fieldCopyUpdates",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceHrefs",
  "relatedSolutionSlugs",
  "relatedInsightSlugs",
]);

export const TEMPLATE_FIELD_LABELS: Record<string, string> = {
  title: "Title",
  description: "Description",
  subtitle: "Subtitle",
  intro: "Intro",
  sectionCopyUpdates: "Section copy updates",
  fieldCopyUpdates: "Field copy updates",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceHrefs: "Related services",
  relatedSolutionSlugs: "Related solutions",
  relatedInsightSlugs: "Related insights",
};

export const TOOL_PROTECTED_FIELDS = new Set<string>([
  ...RESOURCE_CMS_PROTECTED,
  "scoreWeight",
  "weights",
  "signals",
  "questionIds",
  "optionValues",
  "showWhen",
  "storageKey",
  "candidates",
  "eligibility",
]);

/** CMS ToolContent + SEO only — never scoring engine fields */
export const TOOL_FIELD_ALLOWLIST = new Set([
  "title",
  "description",
  "subtitle",
  "intro",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "relatedServiceHrefs",
  "relatedSolutionSlugs",
  "relatedPlatformSlugs",
  "relatedInsightSlugs",
  "questionCopySuggestions",
]);

export const TOOL_FIELD_LABELS: Record<string, string> = {
  title: "Title",
  description: "Description",
  subtitle: "Subtitle",
  intro: "Intro",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  relatedServiceHrefs: "Related services",
  relatedSolutionSlugs: "Related solutions",
  relatedPlatformSlugs: "Related platforms",
  relatedInsightSlugs: "Related insights",
  questionCopySuggestions: "Question copy suggestions (manual engine edit)",
};

export const HOMEPAGE_PROTECTED_FIELDS = new Set([
  "id",
  "updatedAt",
  "updatedById",
  "draftJson",
  "draftUpdatedAt",
  "draftUpdatedById",
  "sectionVisibility",
  "noIndex",
  "canonicalOverride",
  "ogImagePath",
]);

export const HOMEPAGE_FIELD_ALLOWLIST = new Set([
  "heroEyebrow",
  "heroHeadline",
  "heroHeadlineAccent",
  "heroSupporting",
  "primaryCtaLabel",
  "primaryCtaHref",
  "secondaryCtaLabel",
  "secondaryCtaHref",
  "metaTitle",
  "metaDescription",
  "seoTitle",
  "seoDescription",
  "ogTitle",
  "ogDescription",
  "sections",
  "curatedServiceItems",
  "curatedTestimonialIds",
]);

export const HOMEPAGE_FIELD_LABELS: Record<string, string> = {
  heroEyebrow: "Hero eyebrow",
  heroHeadline: "Hero headline",
  heroHeadlineAccent: "Hero headline accent",
  heroSupporting: "Hero supporting",
  primaryCtaLabel: "Primary CTA label",
  primaryCtaHref: "Primary CTA href",
  secondaryCtaLabel: "Secondary CTA label",
  secondaryCtaHref: "Secondary CTA href",
  metaTitle: "Meta title",
  metaDescription: "Meta description",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  ogTitle: "OG title",
  ogDescription: "OG description",
  sections: "Sections",
  curatedServiceItems: "Curated services",
  curatedTestimonialIds: "Curated testimonials",
};

export function filterAllowedFields(
  fields: Record<string, unknown>,
  allowlist: ReadonlySet<string>,
  protectedFields: ReadonlySet<string>,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(fields)) {
    if (protectedFields.has(key)) continue;
    if (!allowlist.has(key)) continue;
    out[key] = value;
  }
  return out;
}
